config/routes.rb
Rails.application.routes.draw do 
  get 'usuarios_administrador/index'
  get 'login/sigin'
  get 'login/cadastrar'
  get 'login/', to: 'login#login'
  post 'logar', to: 'login#logar'
  get 'loja/index', to: 'loja#index'
  get '/loja/locacao/:id', to: 'loja#aluguel'
  get 'login/logout', to: 'login#logout'
  post '/alugar/:id', to: 'loja#alugar'
  get '/confirmacao_pagamento/:reserva_id', to: 'loja#confirmacao_pagamento'
  post 'finalizar_pagamento', to: 'loja#finalizar_pagamento'
  resources :usuarios, except: [:show, :index]
  get 'usuarios', to: 'usuarios_administrador#index'
  get 'administrador/login', to:'login_admistrador#login'
  post 'administrador/logar', to: 'login_admistrador#logar'
  get 'administrador/sair', to: 'login_admistrador#logout'
  resources :usuarios_administradors
  resources :administradors
  resources :reservas, only: [:index, :show]
  resources :clientes
  resources :veiculos
  resources :marcas
  root "loja#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @cliente.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h4>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    
      <%= f.label :nome, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :nome, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :cpf, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :cpf, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :cep, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :cep, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :estado, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :estado, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :rua, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :rua, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @cliente, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing cliente</h1>
</div>

<%= render 'form' %>

app/views/clientes/index.html.erb
<div class="page-header">
  <%= link_to new_cliente_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Cliente
  <% end %>
  <h1>Listing clientes</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome</th>
            <th>Cpf</th>
            <th>Cep</th>
            <th>Estado</th>
            <th>Rua</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @clientes.each do |cliente| %>
        <%= content_tag :tr, id: dom_id(cliente), class: dom_class(cliente) do %>
                      <td><%= cliente.nome %></td>
                      <td><%= cliente.cpf %></td>
                      <td><%= cliente.cep %></td>
                      <td><%= cliente.estado %></td>
                      <td><%= cliente.rua %></td>
                    <td><%= link_to 'Show', cliente %></td>
          <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
          <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/clientes/new.html.erb
<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New cliente</h1>
</div>

<%= render 'form' %>

app/views/clientes/show.html.erb
<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_cliente_path(@cliente), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show cliente</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @cliente.nome %></dd>

  <dt>Cpf:</dt>
  <dd><%= @cliente.cpf %></dd>

  <dt>Cep:</dt>
  <dd><%= @cliente.cep %></dd>

  <dt>Estado:</dt>
  <dd><%= @cliente.estado %></dd>

  <dt>Rua:</dt>
  <dd><%= @cliente.rua %></dd>

</dl>