config/routes.rb
Rails.application.routes.draw do 
  get 'usuarios_administrador/index'
  get 'login/sigin'
  get 'login/cadastrar'
  get 'login/', to: 'login#login'
  post 'logar', to: 'login#logar'
  get 'loja/index', to: 'loja#index'
  get '/loja/locacao/:id', to: 'loja#aluguel'
  get 'login/logout', to: 'login#logout'
  post '/alugar/:id', to: 'loja#alugar'
  get '/confirmacao_pagamento/:reserva_id', to: 'loja#confirmacao_pagamento'
  post 'finalizar_pagamento', to: 'loja#finalizar_pagamento'
  resources :usuarios, except: [:show, :index]
  get 'usuarios', to: 'usuarios_administrador#index'
  get 'administrador/login', to:'login_admistrador#login'
  post 'administrador/logar', to: 'login_admistrador#logar'
  get 'administrador/sair', to: 'login_admistrador#logout'
  resources :usuarios_administradors
  resources :administradors
  resources :reservas, only: [:index, :show]
  resources :clientes
  resources :veiculos
  resources :marcas
  root "loja#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
  belongs_to :marca
end

app/controllers/veiculos_controller.rb
class VeiculosController < AdministradorsController
  before_action :set_veiculo, only: %i[ show edit update destroy ]

  # GET /veiculos or /veiculos.json
  def index
    @veiculos = Veiculo.all
  end

  # GET /veiculos/1 or /veiculos/1.json
  def show
  end

  # GET /veiculos/new
  def new
    @veiculo = Veiculo.new
  end

  # GET /veiculos/1/edit
  def edit
  end

  # POST /veiculos or /veiculos.json
  def create
    @veiculo = Veiculo.new(veiculo_params)

    respond_to do |format|
      if @veiculo.save
        format.html { redirect_to @veiculo, notice: "Veiculo was successfully created." }
        format.json { render :show, status: :created, location: @veiculo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veiculos/1 or /veiculos/1.json
  def update
    respond_to do |format|
      if @veiculo.update(veiculo_params)
        format.html { redirect_to @veiculo, notice: "Veiculo was successfully updated." }
        format.json { render :show, status: :ok, location: @veiculo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veiculos/1 or /veiculos/1.json
  def destroy
    @veiculo.destroy
    respond_to do |format|
      format.html { redirect_to veiculos_url, notice: "Veiculo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veiculo
      @veiculo = Veiculo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def veiculo_params
      params.require(:veiculo).permit(:nome, :cor, :qnt_passageiros, :placa, :valor, :marca_id)
    end
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/veiculos/_form.html.erb
<%= form_for(@veiculo, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @veiculo.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@veiculo.errors.count, "error") %> prohibited this veiculo from being saved:</h4>

      <ul>
      <% @veiculo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    
      <%= f.label :nome, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :nome, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :cor, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :cor, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :qnt_passageiros, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :qnt_passageiros, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :placa, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :placa, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :valor, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :valor, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
      <%= f.label :marca_id, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
       <%= f.select :marca_id, Marca.all.collect{|p| [p.nome, p.id]}, {}, 
        class:"form-control"%>
      </div>
    
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/veiculos/edit.html.erb
<div class="page-header">
  <%= link_to veiculos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @veiculo, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing veiculo</h1>
</div>

<%= render 'form' %>

app/views/veiculos/index.html.erb
<div class="page-header">
  <%= link_to new_veiculo_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Veiculo
  <% end %>
  <h1>Listing veiculos</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome</th>
            <th>Cor</th>
            <th>Qnt passageiros</th>
            <th>Placa</th>
            <th>Valor</th>
            <th>Marca</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @veiculos.each do |veiculo| %>
        <%= content_tag :tr, id: dom_id(veiculo), class: dom_class(veiculo) do %>
                      <td><%= veiculo.nome %></td>
                      <td><%= veiculo.cor %></td>
                      <td><%= veiculo.qnt_passageiros %></td>
                      <td><%= veiculo.placa %></td>
                      <td><%= veiculo.valor %></td>
                      <td><%= veiculo.marca.nome %></td>
                    <td><%= link_to 'Ver', veiculo %></td>
          <td><%= link_to 'Editar', edit_veiculo_path(veiculo) %></td>
          <td><%= link_to 'Deletar', veiculo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/veiculos/new.html.erb
<div class="page-header">
  <%= link_to veiculos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New veiculo</h1>
</div>

<%= render 'form' %>

app/views/veiculos/show.html.erb
<div class="page-header">
  <%= link_to veiculos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_veiculo_path(@veiculo), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show veiculo</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @veiculo.nome %></dd>

  <dt>Cor:</dt>
  <dd><%= @veiculo.cor %></dd>

  <dt>Qnt passageiros:</dt>
  <dd><%= @veiculo.qnt_passageiros %></dd>

  <dt>Placa:</dt>
  <dd><%= @veiculo.placa %></dd>

  <dt>Valor:</dt>
  <dd><%= @veiculo.valor %></dd>

  <dt>Marca:</dt>
  <dd><%= @veiculo.marca.nome %></dd>

</dl>