config/routes.rb
Rails.application.routes.draw do 
  get 'usuarios_administrador/index'
  get 'login/sigin'
  get 'login/cadastrar'
  get 'login/', to: 'login#login'
  post 'logar', to: 'login#logar'
  get 'loja/index', to: 'loja#index'
  get '/loja/locacao/:id', to: 'loja#aluguel'
  get 'login/logout', to: 'login#logout'
  post '/alugar/:id', to: 'loja#alugar'
  get '/confirmacao_pagamento/:reserva_id', to: 'loja#confirmacao_pagamento'
  post 'finalizar_pagamento', to: 'loja#finalizar_pagamento'
  resources :usuarios, except: [:show, :index]
  get 'usuarios', to: 'usuarios_administrador#index'
  get 'administrador/login', to:'login_admistrador#login'
  post 'administrador/logar', to: 'login_admistrador#logar'
  get 'administrador/sair', to: 'login_admistrador#logout'
  resources :usuarios_administradors
  resources :administradors
  resources :reservas, only: [:index, :show]
  resources :clientes
  resources :veiculos
  resources :marcas
  root "loja#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/marca.rb
class Marca < ApplicationRecord
    has_many :veiculos
end

app/controllers/marcas_controller.rb
class MarcasController < AdministradorsController
  before_action :set_marca, only: %i[ show edit update destroy ]

  # GET /marcas or /marcas.json
  def index
    @marcas = Marca.all
  end

  # GET /marcas/1 or /marcas/1.json
  def show
  end

  # GET /marcas/new
  def new
    @marca = Marca.new
  end

  # GET /marcas/1/edit
  def edit
  end

  # POST /marcas or /marcas.json
  def create
    @marca = Marca.new(marca_params)

    respond_to do |format|
      if @marca.save
        format.html { redirect_to @marca, notice: "Marca was successfully created." }
        format.json { render :show, status: :created, location: @marca }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marcas/1 or /marcas/1.json
  def update
    respond_to do |format|
      if @marca.update(marca_params)
        format.html { redirect_to @marca, notice: "Marca was successfully updated." }
        format.json { render :show, status: :ok, location: @marca }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marcas/1 or /marcas/1.json
  def destroy
    @marca.destroy
    respond_to do |format|
      format.html { redirect_to marcas_url, notice: "Marca was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marca
      @marca = Marca.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marca_params
      params.require(:marca).permit(:nome)
    end
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/views/marcas/_form.html.erb
<%= form_for(@marca, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @marca.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@marca.errors.count, "error") %> prohibited this marca from being saved:</h4>

      <ul>
      <% @marca.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    
      <%= f.label :nome, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :nome, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/marcas/edit.html.erb
<div class="page-header">
  <%= link_to marcas_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @marca, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing marca</h1>
</div>

<%= render 'form' %>

app/views/marcas/index.html.erb
<div class="page-header">
  <%= link_to new_marca_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Marca
  <% end %>
  <h1>Listing marcas</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @marcas.each do |marca| %>
        <%= content_tag :tr, id: dom_id(marca), class: dom_class(marca) do %>
                      <td><%= marca.nome %></td>
                    <td><%= link_to 'Show', marca %></td>
          <td><%= link_to 'Edit', edit_marca_path(marca) %></td>
          <td><%= link_to 'Destroy', marca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/marcas/new.html.erb
<div class="page-header">
  <%= link_to marcas_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New marca</h1>
</div>

<%= render 'form' %>

app/views/marcas/show.html.erb
<div class="page-header">
  <%= link_to marcas_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_marca_path(@marca), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show marca</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @marca.nome %></dd>

</dl>