config/routes.rb
Rails.application.routes.draw do 
  get 'usuarios_administrador/index'
  get 'login/sigin'
  get 'login/cadastrar'
  get 'login/', to: 'login#login'
  post 'logar', to: 'login#logar'
  get 'loja/index', to: 'loja#index'
  get '/loja/locacao/:id', to: 'loja#aluguel'
  get 'login/logout', to: 'login#logout'
  post '/alugar/:id', to: 'loja#alugar'
  get '/confirmacao_pagamento/:reserva_id', to: 'loja#confirmacao_pagamento'
  post 'finalizar_pagamento', to: 'loja#finalizar_pagamento'
  resources :usuarios, except: [:show, :index]
  get 'usuarios', to: 'usuarios_administrador#index'
  get 'administrador/login', to:'login_admistrador#login'
  post 'administrador/logar', to: 'login_admistrador#logar'
  get 'administrador/sair', to: 'login_admistrador#logout'
  resources :usuarios_administradors
  resources :administradors
  resources :reservas, only: [:index, :show]
  resources :clientes
  resources :veiculos
  resources :marcas
  root "loja#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/usuarios_administradors_controller.rb
class UsuariosAdministradorsController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]

  
  def index
    @usuarios = Usuario.all
  end

  
  def new
    @usuario = Usuario.new
  end

  
  def edit
  end

  
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        cookies[:usuario] = @usuario.id
        format.html { redirect_to '/', notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    def usuario_params
      params.require(:usuario).permit(:nome, :cpf, :endereco, :numero, :cep, :estado, :login, :senha)
    end
end

app/helpers/usuarios_administrador_helper.rb
module UsuariosAdministradorHelper
end

app/views/usuarios_administradors/_form.html.erb
<%= form_for(@usuario, url: usuarios_administradors_path html: { class: "form-horizontal formUsuario", role: "form" }) do |f| %>
  <% if @usuario.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h4>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    
      <%= f.label :nome, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :nome, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :cpf, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :cpf, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :endereco, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :endereco, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :numero, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :numero, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :cep, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :cep, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :estado, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :estado, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
    <%= f.label :login, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :login, class: "form-control" %>
    </div>
  
  </div>
  <div class="form-group">
    
    <%= f.label :senha, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :senha, class: "form-control" %>
    </div>
  
  </div>

  <div class="form-group">
    <div style='text-align: center;'>
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/usuarios_administradors/index.html.erb
<div class="page-header">
  <%= link_to new_usuarios_administrador_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Usuario
  <% end %>
  <h1>Lista usuarios</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome</th>
            <th>Cpf</th>
            <th>Endereco</th>
            <th>Numero</th>
            <th>Cep</th>
            <th>Estado</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @usuarios.each do |usuario| %>
        <%= content_tag :tr, id: dom_id(usuario), class: dom_class(usuario) do %>
                      <td><%= usuario.nome %></td>
                      <td><%= usuario.cpf %></td>
                      <td><%= usuario.endereco %></td>
                      <td><%= usuario.numero %></td>
                      <td><%= usuario.cep %></td>
                      <td><%= usuario.estado %></td>
                    <td><%= link_to 'Show', usuarios_administrador_path(usuario) %></td>
          <td><%= link_to 'Edit', edit_usuarios_administrador_path(usuario) %></td>
          <td><%= link_to 'Destroy', usuarios_administrador_path(usuario), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/usuarios_administradors/show.html.erb
<div class="page-header">
  <%= link_to usuarios_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_usuario_path(@usuario), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show usuario</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @usuario.nome %></dd>

  <dt>Cpf:</dt>
  <dd><%= @usuario.cpf %></dd>

  <dt>Endereco:</dt>
  <dd><%= @usuario.endereco %></dd>

  <dt>Numero:</dt>
  <dd><%= @usuario.numero %></dd>

  <dt>Cep:</dt>
  <dd><%= @usuario.cep %></dd>

  <dt>Estado:</dt>
  <dd><%= @usuario.estado %></dd>

</dl>